# Generated by Django 4.1.6 on 2023-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名前")),
                ("price", models.PositiveIntegerField(verbose_name="単価")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="登録日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除"),
                ),
            ],
        ),
    ]
