# Generated by Django 4.1.6 on 2023-02-20 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='個数')),
                ('total', models.PositiveIntegerField(blank=True, verbose_name='合計金額')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='販売日時')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mgmt.fruit', verbose_name='果物')),
            ],
        ),
    ]
